# Generated by Django 4.1.1 on 2022-09-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_parada', models.CharField(blank=True, max_length=20)),
                ('data_retorno', models.CharField(blank=True, max_length=20)),
                ('justificativa', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoOnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_online', models.CharField(blank=True, max_length=20)),
                ('acum_maq_parada', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
