# Generated by Django 4.1 on 2022-09-24 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appProducao', '0002_maquinaparada_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaparada',
            name='data_parada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maquinaparada',
            name='data_retorno',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maquinaparada',
            name='justificativa',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='maquinaparada',
            name='op',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
