# Generated by Django 4.1 on 2022-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProducao', '0003_alter_maquinaparada_data_parada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaparada',
            name='status',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
