# Generated by Django 4.1 on 2022-09-24 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appProducao', '0005_alter_maquinaparada_data_parada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaparada',
            name='data_parada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maquinaparada',
            name='data_retorno',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
