# Generated by Django 4.1 on 2022-09-25 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProducao', '0010_alter_maquinaparada_data_parada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaparada',
            name='data_parada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='maquinaparada',
            name='data_retorno',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
