# Generated by Django 4.1 on 2022-08-20 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSecador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura', models.IntegerField()),
                ('pressao', models.IntegerField()),
                ('umidade', models.IntegerField()),
            ],
        ),
    ]
