# Generated by Django 4.1 on 2022-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_op', models.CharField(max_length=20)),
                ('fornecedor', models.CharField(max_length=20)),
                ('largura_capa', models.FloatField()),
                ('comprimento_capa', models.FloatField()),
                ('expessura_capa', models.FloatField()),
                ('qualidade_capa', models.CharField(max_length=20)),
                ('quantidade_producao', models.IntegerField()),
                ('prioridade', models.CharField(max_length=20)),
                ('hora_inicio_prod', models.DateTimeField()),
                ('hora_fim_prod', models.DateTimeField()),
            ],
        ),
    ]
