# Generated by Django 4.1 on 2022-09-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0002_alter_cadastroop_comprimento_capa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroop',
            name='prioridade',
        ),
        migrations.AlterField(
            model_name='cadastroop',
            name='comprimento_capa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroop',
            name='expessura_capa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroop',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroop',
            name='hora_fim_prod',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroop',
            name='hora_inicio_prod',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroop',
            name='largura_capa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroop',
            name='numero_op',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroop',
            name='qualidade_capa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastroop',
            name='quantidade_producao',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
