# Generated by Django 4.1.1 on 2022-09-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0003_remove_cadastroop_prioridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroop',
            name='prod_atual',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
