# Generated by Django 4.1 on 2022-09-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0004_cadastroop_prod_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroop',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
