# Generated by Django 4.1 on 2022-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0005_cadastroop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadMotivoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
