# Generated by Django 4.1 on 2022-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0006_cadmotivoparada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadmotivoparada',
            name='observacao',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
