# Generated by Django 4.1 on 2022-10-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0008_remove_cadmotivoparada_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=25)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('pais', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
