# Generated by Django 4.1 on 2022-10-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0009_cadfornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(blank=True, max_length=50)),
                ('comprimento_tora', models.CharField(blank=True, max_length=50)),
                ('largura_capa', models.CharField(blank=True, max_length=50)),
                ('comprimento_capa', models.CharField(blank=True, max_length=50)),
                ('espessura_capa', models.CharField(blank=True, max_length=50)),
                ('qualidade_capa', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
