# Generated by Django 4.1 on 2022-10-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0010_cadproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ini', models.CharField(blank=True, max_length=50)),
                ('hora_final', models.CharField(blank=True, max_length=50)),
                ('turno', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoraHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(blank=True, max_length=50)),
                ('prod_online', models.CharField(blank=True, max_length=50)),
                ('hora', models.CharField(blank=True, max_length=50)),
                ('turno', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
