# Generated by Django 4.1 on 2022-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0011_cadturno_horahora'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(blank=True, max_length=50)),
                ('horas', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
