# Generated by Django 4.1 on 2022-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0012_horatabela'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadturno',
            old_name='hora_final',
            new_name='hora1',
        ),
        migrations.RenameField(
            model_name='cadturno',
            old_name='hora_ini',
            new_name='hora10',
        ),
        migrations.AddField(
            model_name='cadturno',
            name='hora11',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cadturno',
            name='hora12',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cadturno',
            name='hora2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cadturno',
            name='hora3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cadturno',
            name='hora4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cadturno',
            name='hora5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cadturno',
            name='hora6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cadturno',
            name='hora7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cadturno',
            name='hora8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cadturno',
            name='hora9',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
