# Generated by Django 4.1 on 2022-10-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0013_rename_hora_final_cadturno_hora1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horahora',
            name='data',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
