# Generated by Django 4.1 on 2022-10-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastra', '0014_horahora_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('turno_ini', models.CharField(blank=True, max_length=50)),
                ('turno_fim', models.CharField(blank=True, max_length=50)),
                ('data', models.CharField(blank=True, max_length=50)),
                ('hora', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
